# Generated by Django 6.0.3 on 2026-03-22 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Номер заказа должен содержать только цифры.')], verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_code',
            field=models.CharField(db_index=True, max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Код получения должен содержать только цифры.')], verbose_name='Код получения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('completed', 'Завершен')], db_index=True, default='new', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Артикул содержит только заглавные латинские буквы и цифры.')], verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер 300x200 пикселей.', null=True, upload_to='products/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Наименование'),
        ),
    ]
